version: "3"

services:
  web:
    container_name: "BackEnd-RR-shop-container"
    build: ./web
    volumes:
      - .:/BackEnd
    ports:
      - "8087:8088"
    depends_on:
      - db
    networks:
      - web
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
  db:
    image: mysql:8.0.27
    container_name: "database-RR-shop-container"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: 'db_RR_shop'
      MYSQL_USER: 'viktor'
      MYSQL_PASSWORD: '14051998'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
    networks:
      - web
    volumes:
      - ./db_RR_shop:/var/lib/mysql

networks:
  web:
    driver: bridge
